//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.DONHANGs = new HashSet<DONHANG>();
        }

        [Display(Name = "Mã khách hàng")]//Thuoc tính display dùng để đặt tên lại cho một
        [Required(ErrorMessage ="{0} không được để trống")] // kieemr tra rỗng
        public int MaKH { get; set; }
        [Display(Name = "Họ tên")]//Thuoc tính display dùng để đặt tên lại cho một
        [Required(ErrorMessage = "{0} không được để trống")] // kieemr tra rỗng
        public string HoTen { get; set; }
        [Display(Name = "Tài khoản")]//Thuoc tính display dùng để đặt tên lại cho một
        [Required(ErrorMessage = "{0} không được để trống")] // kieemr tra rỗng
        public string TaiKhoan { get; set; }
        [Display(Name = "Mật khẩu")]//Thuoc tính display dùng để đặt tên lại cho một
        [Required(ErrorMessage = "{0} không được để trống")] // kieemr tra rỗng
        public string MatKhau { get; set; }
        [Display(Name = "Email")]//Thuoc tính display dùng để đặt tên lại cho một
        [Required(ErrorMessage = "{0} không được để trống")] // kieemr tra rỗng
        public string Email { get; set; }
        [Display(Name = "Địa chỉ")]//Thuoc tính display dùng để đặt tên lại cho một
        [Required(ErrorMessage = "{0} không được để trống")] // kieemr tra rỗng
        public string DiaChi { get; set; }
        [Display(Name = "Điện thoại")]//Thuoc tính display dùng để đặt tên lại cho một
        [Required(ErrorMessage = "{0} không được để trống")] // kieemr tra rỗng
        public string DienThoai { get; set; }
        [Display(Name = "Giới tính")]//Thuoc tính display dùng để đặt tên lại cho một
        [Required(ErrorMessage = "{0} không được để trống")] // kieemr tra rỗng
        public string GioiTinh { get; set; }
        [Display(Name = "Ngày sinh")]//Thuoc tính display dùng để đặt tên lại cho một
        [Required(ErrorMessage = "{0} không được để trống")] // kieemr tra rỗng
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Display(Name = "Đơn hàng")]//Thuoc tính display dùng để đặt tên lại cho một
        [Required(ErrorMessage = "{0} không được để trống")] // kieemr tra rỗng

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
    }
}
