//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.THAMGIAs = new HashSet<THAMGIA>();
        }
        [Display(Name="Mã sách")]//Thuoc tính display dùng để đặt tên lại cho một
        public int MaSach { get; set; }
        [Display(Name = "Tên sách")]//Thuoc tính display dùng để đặt tên lại cho một
        public string TenSach { get; set; }
        [Display(Name = "Gía sách")]//Thuoc tính display dùng để đặt tên lại cho một
        public Nullable<decimal> GiaBan { get; set; }
        [Display(Name = "Mô tả")]//Thuoc tính display dùng để đặt tên lại cho một
        public string MoTa { get; set; }
        [Display(Name = "Ảnh bìa")]//Thuoc tính display dùng để đặt tên lại cho một
        public string AnhBia { get; set; }
        [Display(Name = "Ngày cập nhật")]//Thuoc tính display dùng để đặt tên lại cho một 
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        [Display(Name = "Số lượng còn lại")]//Thuoc tính display dùng để đặt tên lại cho một
        public Nullable<int> SoLuongTon { get; set; }
        [Display(Name = "Mã NXB")]//Thuoc tính display dùng để đặt tên lại cho một
        public Nullable<int> MaNXB { get; set; }
        [Display(Name = "Mã chủ đề")]//Thuoc tính display dùng để đặt tên lại cho một
        public Nullable<int> MaChuDe { get; set; }
        [Display(Name = "Mã mới")]//Thuoc tính display dùng để đặt tên lại cho một
        public Nullable<int> Moi { get; set; }
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual CHUDE CHUDE { get; set; }
        public virtual NXB NXB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THAMGIA> THAMGIAs { get; set; }
    }
}
